adding Dag to repo

diff --git a/.github/workflows/terraform-composer-dev.yml b/.github/workflows/terraform-composer-dev.yml
--- a/.github/workflows/terraform-composer-dev.yml
+++ b/.github/workflows/terraform-composer-dev.yml
@@ -1,4 +1,3 @@
-# .github/workflows/terraform-composer-dev.yml
 name: Terraform CI/CD (Composer Dev)
 
 on:
@@ -42,12 +41,19 @@ jobs:
         with:
           terraform_version: 1.6.6
 
-      # Authenticate to Google Cloud using Workload Identity Federation
+      # OIDC auth to GCP (preferred)
       - name: Google Auth (WIF)
         uses: google-github-actions/auth@v2
         with:
-          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
+          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
           service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
+
+      - name: Debug: list files
+        run: |
+          pwd
+          ls -al
+          ls -al environments || true
+          test -f "${{ env.TF_VAR_file }}" && echo "tfvars found" || (echo "tfvars missing"; exit 1)
 
       - name: Terraform Init
         run: |
@@ -91,7 +97,7 @@ jobs:
       - name: Google Auth (WIF)
         uses: google-github-actions/auth@v2
         with:
-          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
+          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
           service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
 
       - name: Terraform Init
